[env:adafruit_itsybitsy_nrf52840]
platform = nordicnrf52
board = adafruit_itsybitsy_nrf52840
framework = arduino
monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 1

; 1. Force the linker to include the TinyUSB library
lib_deps = 
    adafruit/Adafruit TinyUSB Library

; 2. CRITICAL: Prevents the linker from stripping out necessary interrupt handlers
lib_archive = no

; 3. Explicitly tell the core to use TinyUSB
build_flags = 
    -D USE_TINYUSB